### ISSUE TITLE
Conditionals created during an evaluation are not linked to the evaluation

### ISSUE THREAD

**Issue by stevenmirabito** [ComputerScienceHouse/conditional#102]
During intro or membership evaluations, there is an option to conditional a member to some additional requirement. When they complete that requirement, the evals director will pass or fail the conditional on the "Conditionals" page. When this conditional is created during an evaluation, we should link that conditional to the evaluation, and automatically pass/fail the evaluation when the conditional is passed/failed.

The current workaround for this issue is to pass/fail the conditional, then go back to the slideshow and pass/fail the evaluation there.

**Comment by mbillow** [comment]
I am of the thought that this is unnecessary and incredibly complex for us to implement. Defining the object of an evaluation is completely arbitrary. We hold evaluations all of the time (at house meetings and scheduled evaluations), not to mention the results of Eboard decisions. I think the date they were assigned is far more descriptive and helpful that what event the evaluation was assigned at.

**Comment by mbillow** [comment]
We should add a column to the conditional table that is a foreign key to the SpringEval or FreshmanEval (for the sake of clarity, it would actually be two columns). This would allow us to modify the eval result after the end of a conditional.
