### ISSUE TITLE
Changing Housing Points does not work

### ISSUE THREAD

**Issue by mgood15** [ComputerScienceHouse/conditional#111]
When the housing point value is changed in member management and saved, conditional says the update was successful but the housing point number does not actually change even after refreshing the page and clearing the cache.

**Comment by mbillow** [comment]
It is updating them (I just checked LDAP and my number was updated). The problem is with the cache not being cleared after every save.

**Comment by audiolion** [comment]
Looks like we call on the cache [here](https://github.com/ComputerScienceHouse/conditional/blob/cffc62a528432d72699639b065ddde4e7c33e6ae/conditional/util/member.py#L35) calling the `ldap_get_current_students()` method which is an `lru_cache` decorated method. When we [set new housing points](https://github.com/ComputerScienceHouse/conditional/blob/cffc62a528432d72699639b065ddde4e7c33e6ae/conditional/util/ldap.py#L98) we need to call `lru_get_current_students().clear_cache()`. Probably other set methods should clear their appropriate caches as well.

If you want I can submit a PR for this.

**Comment by liam-middlebrook** [comment]
@audiolion yeah that looks about right, and sure PR's are always welcome!

**Comment by mbillow** [comment]
It would be best (for the sake of continuity) to wrap your clearing of the cache in the cache_management blueprint and then call that function when you need.

**Comment by audiolion** [comment]
@mbillow we would need to add some more methods to `cache_blueprint.py` because we don't need to invalidate all the caches in `clear_members_cache()`, is that alright? I mean we can just invalidate everything but when we set housing points I think the only thing we need to clear is `lru_get_current_students`
