### ISSUE TITLE
LDAP_BIND_PW

### ISSUE THREAD

**Issue by audiolion** [ComputerScienceHouse/conditional#114]
Hey guys, when you are setting up the project for development and making your `config.py` what are you supposed to set for the `LDAP_BIND_PW`? I tried the password I use for webauth but it didn't work.

**Comment by liam-middlebrook** [comment]
Are you using your dn for your CSH account?

**Comment by mbillow** [comment]
Yah, your `LDAP_BIND_DN` should be formatted like `uid=XXX,ou=Users,dc=csh,dc=rit,dc=edu`.

**Comment by audiolion** [comment]
The `config.py` defines `LDAP_BIND_DN`as

```
...
LDAP_BIND_DN = 'cn=conditional,ou=Apps,dc=csh,dc=rit,dc=edu'
```

So I assumed that was the binding dn, normally when connecting to csh ldap I would use `uid=rcastner,ou=Users,dc=csh,dc=rit,dc=edu`, so should I replace that then?

**Comment by mbillow** [comment]
Yes

**Comment by audiolion** [comment]
Yeah that worked, mind if I submit a PR to update the config.sample.py?

**Comment by liam-middlebrook** [comment]
I don't think it would make sense to accept that. Unless you just make a comment to note that if developing you may want to use your personal DN. I think it's better to keep the documentation targeted towards deployment in case the bus factor gets a hold of all the current maintainers.

**Comment by mbillow** [comment]
Personally, I don't think changing the sample is necessary. I am fine adding something to the README if others think it is necessary.

**Comment by stevenmirabito** [comment]
A readme update is all that should be necessary here.

**Comment by audiolion** [comment]
I am an idiot, I meant update the README
