### ISSUE TITLE
Local Development Setup - navigating to dashboard on npm start

### ISSUE THREAD

**Issue by audiolion** [ComputerScienceHouse/conditional#115]
Going to localhost:3000 redirects to localhost:3000/dashboard. The dashboard route runs the following:

```
@dashboard_bp.route('/dashboard/')
def display_dashboard():
    log = logger.new(user_name=request.headers.get("x-webauth-user"),
                     request_id=str(uuid.uuid4()))
    log.info('frontend', action='display dashboard')

    # Get username from headers.
    username = request.headers.get('x-webauth-user')

    # Get the list of voting members.
    can_vote = get_voting_members()
    member = ldap_get_member(username)
```

On local though the x-webauth-user header is not set and so when it tries to call `ldap_get_member(username)` username is None and it results in an obvious error.

Tried hacking around it by just doing `ldap_get_member('rcastner')` but it still gave [this traceback](https://gist.github.com/anonymous/4e04c2c1f3b10925a267b5f059af5a05).

**Comment by stevenmirabito** [comment]
You need to fake the header, most of us use this extension: https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj?hl=en

**Comment by mbillow** [comment]
Also, if you have any more questions, feel free to ask in the #conditional channel on Slack! You will probably get a faster answer than here.
