### ISSUE TITLE
Active Membership Button / Export Active Members

### ISSUE THREAD

**Issue by mbillow** [ComputerScienceHouse/conditional#141]
Here is an idea I think would work. Normally the financial director creates a Google Form for people who want to become active. What if we just put a button on the dashboard of everyone in the `current_student` group who is not in the `active` group up until a date defined by the financial director in Member Management. 

Then we have a button for exporting people who are in active status for the Financial Director in Member Management. They can then just send this list to Housing for dues collection. It would streamline the entire process.

**Comment by mbillow** [comment]
@RamZallan I think this is something you could totally work on and would benefit you a lot.

**Comment by csssuf** [comment]
Fixed in #147.
