### ISSUE TITLE
Add way to signify a new year's worth of data

### ISSUE THREAD

**Issue by liam-middlebrook** [ComputerScienceHouse/conditional#15]
This is relatively low-priority, but we need to create an endpoint for the evals director that will change the active tag in all applicable db entries to false.

**Comment by liam-middlebrook** [comment]
Would it make sense to make this a button for the evaluations director to activate at the end of the standard operating session? Or should this be just automated to happen every June 1st? (with the exception of conditionals that have not expire)

**Comment by gambogi** [comment]
The way we approached this in the `csh-eval` data model was to create an evaluations table which had start and end date entries per member, as well as evaluation type (i.e. freshman or membership), and then query for active evaluations based on the date. Projects, seminars, and attendances in that range counted toward that evaluation.

**Comment by liam-middlebrook** [comment]
Interesting. We already have our models with structures in place to do something like this, so the implementation as far as that goes isn't much of a concern. This is really targeting the way for an evals director to signify the change between operating sessions and rather or not it should be automated.

**Comment by gambogi** [comment]
I see. The operating session is fixed to switch every June 1st, and has been for as long as we have record of the constitution, so I think you'd be safe assuming that as a switchover date if you want to do things like show all major projects or evaluations from a particular "year".

**Comment by stevenmirabito** [comment]
I agree, it's easy enough to just filter by things after a certain date. The big task here is going to be adding the UI components and essentially adding pagination by year to the endpoints.

**Comment by liam-middlebrook** [comment]
So there's a few possible solutions I see to this. We could setup a cli option for conditional that is triggered by a cronjob set to execute every June 1st. Or we could expose a form for the evaluations director to set the active field to false appropriately.

**Comment by stevenmirabito** [comment]
Uh, no, neither of those are necessary. The DB queries will have to be updated to select data dated after June 1st of the current year, then we'll either have to do a page-by-page year select dropdown or a session-wide year selection to change what year it looks at.

**Comment by liam-middlebrook** [comment]
Uhh, there's an active field, we should use that as a boolean check since it's faster.

**Comment by stevenmirabito** [comment]
We discussed this and agreed we aren't doing it that way because it makes it much harder to distinguish history. Also, we're already storing dates, and having Postgres SELECT a boolean isn't any slower than having it SELECT rows with a timestamp greater than a certain value.

**Comment by gambogi** [comment]
There's lru caching going on already anyway right? It'd be a pretty easy thing to cache the listings per year, especially for previous years.

**Comment by liam-middlebrook** [comment]
Not for the database. Only for the LDAP queries.
