### ISSUE TITLE
No Favicon

### ISSUE THREAD

**Issue by SethGower** [ComputerScienceHouse/conditional#160]
Doesn't have the same icon as the rest of CSH.

**Comment by mbillow** [comment]
That is statically hosted here: https://assets.csh.rit.edu/uploads/favicon.ico

Feel free to make a PR, the file you want is here: [conditional/conditional/templates/base.html](https://github.com/ComputerScienceHouse/conditional/blob/develop/conditional/templates/base.html)

**Comment by liam-middlebrook** [comment]
Closed via e158fc844c1712c1d11baeaf0f0993f7f63a16bf
