### ISSUE TITLE
Dropdown Arrow does not Expand Information Box in Firefox

### ISSUE THREAD

**Issue by wastevensv** [ComputerScienceHouse/conditional#178]
When I click the dropdown arrow on any page in Firefox, it does not expand the information box contained.

**Comment by wastevensv** [comment]
![image](https://user-images.githubusercontent.com/1253385/38837596-8d8adb72-41a0-11e8-9f48-ed3bde4b59d4.png)
An example of the dropdown arrow I am referring to.

**Comment by devinmatte** [comment]
This was an issue with Firefox not treating the contents of a button object as the clickable item. Fixed in #181
