### ISSUE TITLE
Change "On-Floor" Badge to "On-Floor Status"

### ISSUE THREAD

**Issue by zthart** [ComputerScienceHouse/conditional#179]
Presumably this is because I went on co-op in the spring, but my groups/status on the dashboard are incorrect.

I am neither Active, nor On-Floor. I also don't know how someone can be both active and Non-Voting (unless they were an intro member, but isn't there an intro member status?)

![image](https://user-images.githubusercontent.com/4873335/38883042-d66329c8-4239-11e8-9d3c-625b2bc54414.png)

Not sure where this info gets pulled from, but the app is definitely aware I'm on co-op, as I'm "passing" the Directorship Meetings requirement with 15/15 attended.

**Comment by RamZallan** [comment]
I _think_ `On-Floor` just refers to having on-floor status at all, not living on floor currently. We should probably change that, for clarity.

**Comment by devinmatte** [comment]
These more accurately mean:
`On-floor`: On floor status
`Active`: Being evaluated at Spring Evals
`Non-Voting`: Haven't paid dues this semester/on co-op

I agree these badges should be more clear in how they're displayed. They can be a bit confusing. We should probably update the language a bit

**Comment by mbillow** [comment]
You can be on-floor and active. https://github.com/ComputerScienceHouse/Constitution/blob/d3936b883574b775f0170c2b5266117bbb52ad05/articles.tex#L202

I am fine changing `On-floor` to `On-floor Status`, but the other's are correct.

**Comment by zthart** [comment]
Why not combine the Active and Non-Voting tags to just one that says On Co-op. From the line linked in the constitution that appears to be the only scenario in which you are active but have no voting rights

**Comment by mbillow** [comment]
Verbosity, I guess. I'm not going to say it should be one way or the other, both are correct.

**Comment by zthart** [comment]
Huh. man groups are wild. 

Welp, I guess there's not really an issue here, unless someone really wants to make the On-floor change to On-Floor Status. Go ahead and slap me with that wontfix or close it if you'd like, unless you want to attach the change in verbiage of the on-floor label to this issue.

**Comment by mbillow** [comment]
I'll leave it up to the person who wants to make the change.

**Comment by zthart** [comment]
Related thought - again, not at all a web developer. Why not add hover text to each of the badges that says what they actually mean. 

So like Active would say "Active for all/part of this operating session" or some shit like that on hover
