### ISSUE TITLE
Homepage is extremely redundant

### ISSUE THREAD

**Issue by TalCohen** [ComputerScienceHouse/conditional#27]
There is a lot of redundant information on the homepage about telling me that I haven't missed any house meetings, gone to any committee meetings, or passed a major project.

**Comment by mbillow** [comment]
It seems weird to just omit the panel if there is no information, especially since the warnings are valid. Old evals would just show an empty table with headers, displaying a message seems more user friendly than hiding it altogether.

**Comment by mbillow** [comment]
It is also worth mentioning that this is only there because it is the start of the year. As committee meetings happen and major projects are submitted, these elements will be replaced by appropriate tables.
