### ISSUE TITLE
All instances of "committee" should be changed to "directorship"

### ISSUE THREAD

**Issue by TalCohen** [ComputerScienceHouse/conditional#28]
Everywhere that it says the word "committee" like in committee meetings, it should be changed to "directorship" like in directorship meetings. The reason they were committee meetings in evals is because that was before we voted in the change.

**Comment by mbillow** [comment]
Committee has become a cultural word, post constitutional change. We still say we have committee meetings even though it is definitely a directorship. I am impartial either way, but to be correct, it should say directorship.

**Comment by stevenmirabito** [comment]
They are worded as "directorships" in the Constitution now, right? If so, I agree the wording should be updated. I also think that this should be updated in LDAP too if that's the case, but I know that's easier said than done.

**Comment by TalCohen** [comment]
They are now directorships, correct. Committee's are a thing that can be formed, but they are not what you are referring to in Conditional.

**Comment by mbillow** [comment]
:+1: should be a quick fix!
