### ISSUE TITLE
Spring Evals "Not Applicable" for Inactive Members

### ISSUE THREAD

**Issue by VictoriaWeaver** [ComputerScienceHouse/conditional#34]
The "Pending" label is odd for inactive members, maybe add a "Not Applicable" state instead

**Comment by liam-middlebrook** [comment]
Is this in reference to the dashboard?

**Comment by VictoriaWeaver** [comment]
yes

**Comment by stevenmirabito** [comment]
I think this could be solved by simply hiding the panels altogether for inactive members, in which case I would prefer using #36 and closing this as a duplicate.

**Comment by mbillow** [comment]
This is intended behavior, inactive members are eligible for meeting attendance and this is recorded just in case they plan on paying dues. Now, if someone isn't in the current_student LDAP group, they shouldn't see the warnings.

**Comment by TalCohen** [comment]
I'm with Victoria here. It is very odd to see "pending" when you aren't actually currently coming up for membership evaluations. See the attached image.

I don't think this box should even show up if you're not an active member. Thoughts?

<img width="569" alt="screen shot 2016-08-23 at 10 54 30 am" src="https://cloud.githubusercontent.com/assets/2976769/17896873/23dba80a-6920-11e6-88a8-fbed4fe47373.png">

**Comment by VictoriaWeaver** [comment]
I don't mind the table being visible , especially since you can still submit major projects as an inactive member so seeing that status would be useful.  My main concern is the table header 

![image](https://cloud.githubusercontent.com/assets/6857477/17897310/b4f1ce9a-6921-11e6-8faf-950df977e750.png)

and the warnings.

![image](https://cloud.githubusercontent.com/assets/6857477/17897567/9cefe5b0-6922-11e6-853a-66f134319317.png)

 I would just chance the icon and switch from "Pending" to "Not Applicable" or some equivalent and hide the warnings. The current setup can be confusing because it looks like you're coming up for vote even though you're inactive, which would be concerning for someone planning on resuming membership at some point (e.g. next year).

**Comment by TalCohen** [comment]
So would there be any point in showing *any* of the boxes? Like none of them pertain to non-active members. But then we're just left with the header box of the name whatnot... Thoughts?

**Comment by VictoriaWeaver** [comment]
Well like I said before, the major project box does apply because inactive members can submit major projects, so I think that should be there to see in case someone does decide to do that.  Maybe for meetings set the requirements to "N/A" or "0/0".

Or maybe only display the major project box if one is submitted?

**Comment by mbillow** [comment]
<img width="1162" alt="screen shot 2016-10-18 at 23 35 35" src="https://cloud.githubusercontent.com/assets/8651166/19504843/9e37adfa-958b-11e6-8de7-710a257875df.png">
As you can see above, I hid the evaluation status and irrelevant information from the housing panel. I think the major project banner is still relevant though, since most people  who are using Conditional who are in an inactive state are looking into become active.

**Comment by gambogi** [comment]
> most people who are using Conditional who are in an inactive state are looking into become active. 

I don't think there's a reasonable basis for this assumption. People who aren't active don't have requirements. Why show anything other than current status, housing points, and a listing of major projects?
Inactive people don't get meeting credit while inactive so why have that count? Even if they're thinking about becoming active as you say, that number is obviously zero. House meetings missed also doesn't make a ton of sense. It's just not relevant content.

**Comment by liam-middlebrook** [comment]
To clarify:

> Inactive people don't get meeting credit while inactive so why have that count?

Inactive people don't get house meeting attendance. However, they are able to get attendance for seminars and directorship meetings.

**Comment by gambogi** [comment]
That attendance shouldn't count toward any evaluation though, so it's still not super relevant in a checkmarky sense (i.e. n/25)

**Comment by VictoriaWeaver** [comment]
Has this been applied?  I don't see any difference on my dashboard.

**Comment by mbillow** [comment]
The changes are currently only in the development environment (https://conditional-dev.csh.rit.edu). They will be pulled into production in our next version release.
