### ISSUE TITLE
Major Project failed submission alert message is ambiguous

### ISSUE THREAD

**Issue by VictoriaWeaver** [ComputerScienceHouse/conditional#35]
If there's a reason why the submission failed, list the reason so it can be fixed.
e.g. "Your project name is blank!  Please give it a name."

**Comment by stevenmirabito** [comment]
This is currently difficult because we don't have proper form validation on the backend. We can add some basic checks in the frontend, but I don't want to have full blown frontend form validation if we're going to move to validating payloads (and returning proper error messages) on the backend.

**Comment by mbillow** [comment]
This is just an example of what will be fixed with #17 is completed. Once payload validation is implemented, this will be solved.
