### ISSUE TITLE
Ping in a channel when a major project is submitted

### ISSUE THREAD

**Issue by WillNilges** [ComputerScienceHouse/conditional#359]
Write a slackbot that integrates with Conditional that pings in `#current-eboard` when someone submits a project for our review. That way the onus is on eboard to reach out in DMs, but we all _actually_ get notified when someone is ready to submit. Couple this with #48, and we'd have a much more robust process for creating Major Project proposals that are better for everyone.

**Comment by ethanf108** [comment]
> Write a slackbot that integrates with Conditional that pings in `#current-eboard` when someone submits a project for our review. That way the onus is on eboard to reach out in DMs, but we all _actually_ get notified when someone is ready to submit. Couple this with #48, and we'd have a much more robust process for creating Major Project proposals that are better for everyone.

I would recommend either posting to #major-projects, or a new eboard-only channel specifically for major project notifications. Pinging #current-eboard would pollute it.

**Comment by jabbate19** [comment]
Best practice is likely making the `CHANNEL_ID` a config variable so if we need to change it later it doesn't require a commit

**Comment by Mstrodl** [comment]
Please don't use a slack bot for this, use a webhook or a workflow!
![image](https://user-images.githubusercontent.com/6877780/186706504-cda5e2ed-ad9c-432a-bca6-3ba66f150f2e.png)
