### ISSUE TITLE
Eval progress not relevant to non-active members

### ISSUE THREAD

**Issue by gambogi** [ComputerScienceHouse/conditional#36]
![eval_progress_alum](https://cloud.githubusercontent.com/assets/1028704/17869994/799ff9a0-686a-11e6-9422-821100dd7647.png)

This shouldn't be displayed if a member is not pursuing an evaluation

**Comment by liam-middlebrook** [comment]
Directly related to #34

**Comment by mbillow** [comment]
Please reference #34.
