### ISSUE TITLE
Profile Image display not internally consistent

### ISSUE THREAD

**Issue by gambogi** [ComputerScienceHouse/conditional#37]
Sometimes displayed as a circle, sometimes as a square
![conditional-profile-matchyness](https://cloud.githubusercontent.com/assets/1028704/17870032/a47ce69c-686a-11e6-828f-aae96df7347e.png)

**Comment by stevenmirabito** [comment]
Is there a design guideline that we should be following for this @mbillow? This really doesn't bother me at all.

**Comment by mbillow** [comment]
I mean, I think each format has its own benefits... If we want to standardize, they should all be circles. That is how they are in Discourse and we should keep that theme going forward.

PS: We should make a few CSH Bootstrap pages in the Style Guide and cover this kind of thing.

**Comment by mbillow** [comment]
![image](https://cloud.githubusercontent.com/assets/8651166/17909411/6a7df718-6952-11e6-8baf-3bb08449dcc4.png)
Done.

**Comment by stevenmirabito** [comment]
I really, really don't like this. Can we discuss this please?

**Comment by mbillow** [comment]
I actually really, really like this. What don't you like about it?

**Comment by liam-middlebrook** [comment]
I vaguely remember a design that looked like this (but actually good) for the profile banner. That way the images could still be square (with the exception of this banner)
![image](https://cloud.githubusercontent.com/assets/3920942/18147852/79ee8e6c-6fa4-11e6-9d64-5b86fa54441f.png)

**Comment by stevenmirabito** [comment]
Closing as this has been resolved in #46. If we want to revisit the design of the dashboard user panel, we can do so at a later date.
