### ISSUE TITLE
Conditional Form

### ISSUE THREAD

**Issue by mbillow** [ComputerScienceHouse/conditional#49]
So it turns out it is hard to create a conditional in conditional outside of normal evals presentations. We need a conditional form in conditional that allows the evals director to submit / update a conditional in the conditional db so all members can see the status of a conditional when accessing conditional.

**Comment by jeid64** [comment]
We need a conditional to submit a conditional into conditional on the
condition that a conditional is available.

**Comment by mbillow** [comment]
I added the actual form in the conditional-form branch on commit c5f7c439a8363ca04d3b0dc17ec11878cda0b353. @stevenmirabito If you want to make the form actually submit, that would be great appreciated. We also then need to use the modal so you can update a conditional after submission.

**Comment by stevenmirabito** [comment]
Opened a #68 to fix this issue.
