### ISSUE TITLE
Improve eval-info label aesthetics 

### ISSUE THREAD

**Issue by gambogi** [ComputerScienceHouse/conditional#53]
![image](https://cloud.githubusercontent.com/assets/1028704/18278271/7150e1a4-741f-11e6-9d43-179d48e6fc02.png)

Issues I have with the current design: 
- Visually loud and jarring use of bold red and green (heyooo zookeeper)
- Tabular data (requirement: status) not being displayed as such
- Requirements in progress (such as freshman project) marked red "danger" despite db knowledge of pending status

I'd prefer a similarly sized table without the background colors, but with data and a status icon rather than the christmas tree. 

Might also be good to list the threshold for things like meeting/seminar attendance. So "committee meetings 9/10" would be listed in this screenshot.

**Comment by mbillow** [comment]
So, in the past few revisions we have improved this section a bit. We addressed the third point completely. It is possible to implement a toggle to switch between table and card view, but the data we are displaying here is (in my opinion) way too much for a table. Especially if we are going to continue to explore additions like #48, the card layout is going to be the only proper way to display all of the data. 

As the year goes on and more and more people start meeting their requirements there becomes less red which is the visually jarring part in my opinion. Take my card as an example:

<img width="700" alt="screen shot 2016-10-17 at 13 33 02" src="https://cloud.githubusercontent.com/assets/8651166/19448094/4ca8e1fc-946e-11e6-80f6-0f3c504b3331.png">

When you have completed your requirements, it is no longer jarring and conveys the message we are trying to get across. When you have missing requirements, it should be highlighted and I think this design does that.

Take these two cards for example. Personally, I think they encompass exactly what they should with the colors they are using.

<img width="330" alt="screen shot 2016-10-17 at 13 37 48" src="https://cloud.githubusercontent.com/assets/8651166/19448253/09d711fe-946f-11e6-818f-61373f92caed.png"><img width="330" alt="screen shot 2016-10-17 at 13 37 24" src="https://cloud.githubusercontent.com/assets/8651166/19448257/0fc5bd4a-946f-11e6-9555-e09918a040c6.png">

And on the last note: that is something that would take two seconds to incorporate. It is actually just adding text to the templates.

**Comment by gambogi** [comment]
Glad the pending pending issue was addressed.
When you say "card layout" I assume you're talking about the panels for each person? I totally agree with that. The panels look great outside of this status issue. By tabular I didn't mean go back to the old spreadsheet view of old evals, rather something more like this:
![image](https://cloud.githubusercontent.com/assets/1028704/19450667/5c2fb75e-9478-11e6-8cd0-84b3abb912d5.png)

The specific things I'm going for here are visual alignment of like data. Field labels are aligned with each other, field values can be scanned quickly, and how it relates to the actual requirement is obvious. The pass/fail/pending status can still be conveyed with an icon on the result "column".

As far as the colors go, it's not so much that they're jarring (they are), but they have terrible contrast with the text, which makes them difficult to read. As a not web developer, I tried to look something up to back up this point, and at the very least this tool (http://webaim.org/resources/contrastchecker/) confirms what I thought. I did a quick check on the white on red, and it doesn't pass thew Web Accessibility guidelines or something. Point is there is a formula that backs up this being difficult to read.

Aside from that, using green and red to indicate success or failure is possibly the biggest middle finger to give to colorblind users.

**Comment by mbillow** [comment]
> Aside from that, using green and red to indicate success or failure is possibly the biggest middle finger to give to colorblind users.

Have you met @liam-middlebrook? I'm not saying it was intentional or anything but... 😜 

On a more serious note, these colors are directly from the Google Material design guide. https://material.google.com/style/color.html They are paired with the suggest text color for maximum readability. 

If red and green aren't your preffered colors, I'm interested to know what you would suggest.

**Comment by gambogi** [comment]
Sorry, my criticism would have been more precise as "... **only** using green and red ..." 
I would suggest using the icons as you do on the dashboard, and continue using red and green if you like (although personally I'd favor deeper shades). It's great those colors are pulled from Google, but the font size used in those demos is 14px, whereas I think the font here is closer to like 9px or 10px. That makes a big difference in legibility. 

The fact that nothing is aligned also just makes these blocks of information difficult to parse. It's somewhat to tell at a glance what value of each requirement is.

**Comment by ajgajg1134** [comment]
I don't believe these colors are actually directly from the material design guide (well, I can't seem to find them) but at a cursory glance at the design guide it actually appears that we should be using black text color inside. IMHO it is much easier to read this way (Or we can switch to darker greens and reds, I have no strong opinion other than agreeing with Gambogi that the contrast isn't sufficient)

![jarring](https://cloud.githubusercontent.com/assets/2355709/19454716/39818ae2-9488-11e6-9488-42265ef8d895.PNG)

**Comment by mbillow** [comment]
<img width="962" alt="screen shot 2016-10-18 at 00 52 00" src="https://cloud.githubusercontent.com/assets/8651166/19464800/1c593088-94cd-11e6-9573-c90306bec94d.png">
@gambogi @ajgajg1134 Better?

**Comment by gambogi** [comment]
That looks great, thanks @mbillow!

**Comment by mbillow** [comment]
This will be pulled into the next release of Conditional.
