### ISSUE TITLE
Way to view required quorum numbers

### ISSUE THREAD

**Issue by ajgajg1134** [ComputerScienceHouse/conditional#67]
Basically just a page that shows the number of members required to meet various quorum requirements (The same as original evals db site)

**Comment by liam-middlebrook** [comment]
This is currently a feature viewable only by the evaluations and financial directors.

**Comment by ajgajg1134** [comment]
Is there a reason it isn't just view-able to everyone?

**Comment by stevenmirabito** [comment]
Specifically:

![](http://i.imgur.com/6CKVgYb.png)

**Comment by ajgajg1134** [comment]
Additionally to that bar, I would like the actual numbers (and math done) to show each category of quorum requirement and the number of members.

**Comment by liam-middlebrook** [comment]
To clarify, the numbers above are from a development instance and are not a direct correlation to CSH's current membership statistics.

**Comment by mbillow** [comment]
Will be pulled into production in our next release. Thank you for the feedback.
