### ISSUE TITLE
Make Housing Queue re-organizable List

### ISSUE THREAD

**Issue by liam-middlebrook** [ComputerScienceHouse/conditional#70]
This would probably be what we want for the frontend. At least in terms of user experience / flow.
http://farhadi.ir/projects/html5sortable/

I'm not sure how we'd implement this in the backend (because we wouldn't want to have to change the entire list sorting each time) So it'll be interesting seeing how postgres will handle this kind of data format of a linked list.

**Comment by mbillow** [comment]
There is no point where the Evals director has the ability to re-arrange the housing queue. It is very much a procedural process. The solution is not to add more user intervention, but rather ensure our data is correct and we cover all the situations that are factored into calculating the housing queue.

**Comment by stevenmirabito** [comment]
I agree with @mbillow. I just merged #71 into develop which should fix the problem we were having with the housing queue.
