### ISSUE TITLE
Move LDAP diff checking into the LDAP class methods

### ISSUE THREAD

**Issue by stevenmirabito** [ComputerScienceHouse/conditional#72]
We shouldn't have blocks of code in our controllers checking to see if there's an LDAP diff. In fact, I'm not sure it's worth our time to actually check if there's a diff because if there is we're making 2 LDAP requests instead of one. If we do decide to check, that logic should be moved into the LDAP methods themselves to abstract it away from the controllers.

I have a a somewhat large refactoring of the LDAP util coming down the pipe, so we should hold off on this until that's merged.

**Comment by liam-middlebrook** [comment]
I'm not sure that the Eval Presentation Milestone (Conditional 1.2) is the proper place for this issue to be prioritized. I'll remove it from that milestone in a few hours if no objections are brought up.

**Comment by mbillow** [comment]
Speaking of large LDAP refactors.... ;) @liam-middlebrook's library checks all changes before making them. (adding/removing from groups, setting attributes, etc.)

With #104 being merged into develop, I think it is safe to close this.
