### ISSUE TITLE
Add Way for Evaluations Director to Change Freshman Project Status

### ISSUE THREAD

**Issue by liam-middlebrook** [ComputerScienceHouse/conditional#73]
Freshman Project Status.

Right now there's no way for the evals director to set whether or not a member passed freshman project.

**Comment by mbillow** [comment]
We should provide an interface to the Evals director similar to major projects (just more compact, since there is less/no data to display) or maybe a page similar to house meeting attendance with either three radio buttons (Pass, Fail, Pending) or a dropdown next to each freshmen. @stevenmirabito thoughts?

**Comment by stevenmirabito** [comment]
How do we determine if a member is an intro member? This should probably be another checkbox in the member management modal and/or in the member management table. I think a whole new page is unnecessary.

**Comment by mbillow** [comment]
My goal in adding a new page was to speed up the process of data entry. If you have to manually go to all 60 intro member modals on the member management page change they status, save, find the next and repeat it would take a very long time to enter the data. Whereas, if there was a page for it, you could just enter all the data and submit.

**Comment by stevenmirabito** [comment]
Yeah, I was thinking that too. I just don't want to make it too spread out. We could do something similar to the conditionals page.

**Comment by mbillow** [comment]
Yah, that is very similar to the former part of my suggestion.

**Comment by mbillow** [comment]
Solved by #88
