### ISSUE TITLE
Co-Op Submission / Entry

### ISSUE THREAD

**Issue by mbillow** [ComputerScienceHouse/conditional#80]
So, I have been thinking about how we want to handle the entry of co-ops into Conditional. Personally, it makes sense to me to have the user submit their co-op start and end dates and then for the Evals director to approve them (so a user can't enter a false co-op). We could have a page (under Forms) for submission and then just show a banner for the Evals director on their Dashboard with an approve or reject button.

**Comment by liam-middlebrook** [comment]
I like the idea of having a banner on the dashboard to convey this information to the evals director. My only concern would be that this information may take up more than a mobile-friendly amount of space on the dashboard.

I definitely agree that this should be a system that has the Evals director vet a members co-op. Whether that person submits the co-op to the evals director in Conditional, or through another medium by which the Evals director will then go on to enter into Conditional I'm not sure. The first seems like a more elegant solution and then ties in common concepts from past discussions I've had about technical seminar attendance submission queuing.

**Comment by audiolion** [comment]
We could potentially just plug this into the co-op system that RIT uses, it was built by a student, we could see if we can get an API to check against. It would provide another form of verification or a single source of truth for co-ops. Also makes sure people are doing the right things when going on co-op (applying and registering it correctly through RIT's systems)
