### ISSUE TITLE
Trouble during local setup - `flask zoo`

### ISSUE THREAD

**Issue by audiolion** [ComputerScienceHouse/conditional#86]
Followed the README, got to the instructions
```
pip install pymysql
flask zoo
```

When running `flask zoo` I get the following
```
Usage: flask db [OPTIONS] COMMAND [ARGS]...

Error: No such command "zoo".
```

I see that zoo is located in the ``__init__.py`` of conditional so I tried some variations ``flask conditional.zoo`` and the like to no avail. I am on `python 3.5.1` and not `3.5.2`, only discrepancy between my local setup and instructions (which state to have the latest version of python 3)

**Comment by stevenmirabito** [comment]
Those instructions are outdated and should be updated. You can skip that step entirely, it's only necessary if you want to run a database migration from the old Evals DB.
