### ISSUE TITLE
Enable Docker/OpenShift Compatibility

### ISSUE THREAD

**Issue by stevenmirabito** [ComputerScienceHouse/conditional#91]
Add the ability to deploy Conditional with Docker on CSH OpenShift. A `Dockerfile` has already been written and most of the work has been completed on the `docker` branch, but as with #90 it will need to be rebased onto the current code.

**Comment by mbillow** [comment]
@stevenmirabito Any idea when you are going to get this done?

**Comment by liam-middlebrook** [comment]
I think it may be a better idea to hold off on this in the interest of not rushing changes into production. I think this is definitely where conditional will end up in the future, but I don't think that we'll be able to get rigorous enough testing and the uptime that we've had if we move over to openshift and oidc in less than a week.

Ideally I'd like to see oidc auth support a way to "disable auth" through it's actual mechanism, and then fake a oidc session object/dictionary based on request headers.

**Comment by mbillow** [comment]
Fixed by #171
