### ISSUE TITLE
Conditionals not displayed with associated Evaluation

### ISSUE THREAD

**Issue by gambogi** [ComputerScienceHouse/conditional#99]
When looking at the list of conditionals, it isn't possible to discern the kind of evaluation that a person was conditionaled for.

**Comment by mbillow** [comment]
I'm not sure the value of this? Does the date assigned not provide enough context?

**Comment by gambogi** [comment]
Nope, because sometimes the date of entry is later than the date the conditional was actually assigned. The particular case that this applies to was a conditional from earlier in semester that wasn't entered until the same day as introductory evals, so it looked like it was for the same batch, despite being for a different evaluation.

**Comment by mbillow** [comment]
Honestly, I think that is a special case. Meghan would have put that in immediately had the form existed.

**Comment by mbillow** [comment]
Future changes regarding this issue will be tracked in #102.
